### ISSUE TITLE
Modite detail view animation does not take into account slow networks

### ISSUE THREAD

**Issue by jaygarcia** [ModusCreateOrg/modir#41]
On slow networks, the images are loaded on detail views, but after some time, the animation shows images for prior detail views.  I noticed this without throttling, which is why I'm reporting. Using "Fast 3G" within Chrome helps display the lag time more.

Steps to reproduce:

- Launch app
- pop open chrome debugger & setup network to "Fast 3G"
- *Hard* Invalidate cache by spamming `CMD + SHIFT + R` 3 - 4 times quickly. (sometimes, hitting the key combo a single time really doesn't do the job well. :( )
- Load one or two detail views on the top of the list
- Scroll > 50% of the list
- Load some detail views.

Demo:
![Apr-25-2019 12-59-32](https://user-images.githubusercontent.com/180031/56754244-8a81f100-675a-11e9-9811-fe4da684076f.gif)

**Comment by mitchellsimoens** [comment]
As I mentioned in another issue (#40) the way we were showing details view and such wasn't using react-router properly. The detail view was always created and just got the new modite so it could update the info and picture. The animation in would occur regardless of loading state. Now, we are using react-router to switch screens, we have page transitions (thanks to [`react-transition-group`](https://www.npmjs.com/package/react-transition-group)) and we are using Suspense that helps with handling loading state.

So after the refactoring, the detail view is only shown when on the route which means it will only render what the route is on. While the image loads, it will have a white background till it loads instead of showing the last image as there is no last image.
